USE [master]
GO

/****** Object:  Database [ComputersDb]    Script Date: 8.11.2016 ã. 18:19:12 ÷. ******/
CREATE DATABASE [ComputersDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ComputersDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ComputersDb.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ComputersDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ComputersDb_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ComputersDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ComputersDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ComputersDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ComputersDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ComputersDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ComputersDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ComputersDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [ComputersDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ComputersDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ComputersDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ComputersDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ComputersDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ComputersDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ComputersDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ComputersDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ComputersDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ComputersDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ComputersDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ComputersDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ComputersDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ComputersDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ComputersDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ComputersDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ComputersDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ComputersDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ComputersDb] SET  MULTI_USER 
GO

ALTER DATABASE [ComputersDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ComputersDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ComputersDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ComputersDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ComputersDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ComputersDb] SET QUERY_STORE = OFF
GO

USE [ComputersDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ComputersDb] SET  READ_WRITE 
GO


